[plugins]
# Rocks.nvim and addons
"rocks.nvim" = "2.36.0"
"rocks-config.nvim" = "2.2.0"
"rocks-git.nvim" = "2.0.1"
"rocks-treesitter.nvim" = "1.0.3"
"rocks-dev.nvim" = "1.3.0"

# Treesitter parsers
tree-sitter-toml = "0.0.2"

"oil.nvim" = "2.11.0"
"lazygit.nvim" = "scm"

[config]
plugins_dir = "plugins/"
auto_setup = true

[treesitter]
auto_highlight = "all"
auto_install = "true"
