[plugins]
# Rocks.nvim and addons
"rocks.nvim" = "2.36.1"
"rocks-config.nvim" = "2.2.0"
"rocks-git.nvim" = "2.0.1"
"rocks-treesitter.nvim" = "1.0.3"
"rocks-dev.nvim" = "1.3.0"

"oil.nvim" = "2.11.0"
"which-key.nvim" = "3.13.2"
"nvim-web-devicons" = "0.100"

"mason.nvim" = "1.10.0"
"mason-lspconfig.nvim" = "1.30.0"
nvim-lspconfig = "0.1.8"
nvim-cmp = { git = "hrsh7th/nvim-cmp", rev = "main"}
"conform.nvim" = "7.0.0"
nvim-lint = "scm"
cmp-nvim-lsp = "scm"

"lazygit.nvim" = "scm"
"telescope.nvim" = "scm"
"barbecue.nvim" = "scm"

# Treesitter parsers
"tree-sitter-toml" = "0.0.2"
tree-sitter-json = "0.0.2"
tree-sitter-nix = "0.0.4"
tree-sitter-rust = "0.0.2"

[plugins."gitsigns.nvim"]
git = "github:lewis6991/gitsigns.nvim"
rev = "v0.9.0"


[plugins.editorconfig-vim]
git = "editorconfig/editorconfig-vim"
rev = "v1.2.0"


[bundles.lsp]
items = [
    "mason.nvim",
    "mason-lspconfig.nvim",
    "nvim-lspconfig",
    "nvim-cmp",
    "conform.nvim",
    "nvim-lint",
    "cmp-nvim-lsp"
]

[bundles.ui]
items = [
    "barbecue.nvim",
]

[config]
plugins_dir = "config/"
auto_setup = true

[treesitter]
auto_highlight = "all"
auto_install = "true"
